let data = {
  team: [
    {
      id: 1,
      name: 'Saing Sopheak',
      role: 'Backend & Server Side',
      image: '/my-app/public/images/sopheak.jpg',
      email: '<EMAIL>',
      phone: '<PHONE>',
      address: '<ADDRESS>',
      city: '<CITY>',
      state: '<STATE>',
    },
    {
      id: 2,
      name: 'Backend and Server',
      role: 'BackEnd',
      image: '/my-app/public/images/koemnak.jpg',
      email: '<EMAIL>',
      phone: '<PHONE>',
      address: '<ADDRESS>',
      city: '<CITY>',
      state: '<STATE>',
    },
    {
      id: 3,
      name: 'Sou Many',
      role: 'Frontend and Responsive<',
      image: '/my-app/public/images/soumany.jpg',
      email: '<EMAIL>',
      phone: '<PHONE>',
      address: '<ADDRESS>',
      city: '<CITY>',
      state: '<STATE>',
    },
    {
      id: 4,
      name: 'Som Sodana',
      role: 'Frontend',
      image: '/my-app/public/images/sodana.jpg',
      email: '<EMAIL>',
      phone: '<PHONE>',
      address: '<ADDRESS>',
      city: '<CITY>',
      state: '<STATE>',
    },
    {
      id: 5,
      name: 'Srun Chhaylin',
      role: 'Testing and Hosting',
      image: '/my-app/public/images/chhaylin.jpg',
      email: '<EMAIL>',
      phone: '<PHONE>',
      address: '<ADDRESS>',
      city: '<CITY>',
      state: '<STATE>',
    },
  ],
};
